<a href="https://colab.research.google.com/github/d12eek/ANN-And-DL-Lab-24mcs005/blob/main/MLP_Optimizers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.datasets import make_regression
from sklearn import metrics
from sklearn import decomposition
from sklearn import manifold
from tqdm.notebook import trange, tqdm

#TensorFlow and Keras Libraries
import tensorflow as tf
from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model
import torch
from torchvision import transforms
from tensorflow.keras.utils import to_categorical
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data
import torchvision
import torchvision.datasets as datasets
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import os

# Hiding the warnings
import warnings
warnings.filterwarnings('ignore')

# Extra Libraries
import copy
import random
import time

In [3]:
file_path = '/content/house-prices.csv'
df = pd.read_csv(file_path)

In [4]:
df.shape

(128, 8)

In [5]:
df.head()

,Home,Price,SqFt,Bedrooms,Bathrooms,Offers,Brick,Neighborhood
0,1,114300,1790,2,2,2,No,East
1,2,114200,2030,4,2,3,No,East
2,3,114800,1740,3,2,1,No,East
3,4,94700,1980,3,2,3,No,East
4,5,119800,2130,3,3,3,No,East


In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Home          128 non-null    int64 
 1   Price         128 non-null    int64 
 2   SqFt          128 non-null    int64 
 3   Bedrooms      128 non-null    int64 
 4   Bathrooms     128 non-null    int64 
 5   Offers        128 non-null    int64 
 6   Brick         128 non-null    object
 7   Neighborhood  128 non-null    object
dtypes: int64(6), object(2)
memory usage: 8.1+ KB


In [7]:
df.isna().sum()

,0
Home,0
Price,0
SqFt,0
Bedrooms,0
Bathrooms,0
Offers,0
Brick,0
Neighborhood,0


In [8]:
cat_col = []
for i in df.columns:
    if df[i].dtype == 'O':
        cat_col.append(i)

cat_col

['Brick', 'Neighborhood']

In [9]:
df['Brick'].value_counts()

,count
Brick,
No,86
Yes,42


In [10]:
df[cat_col].nunique()

,0
Brick,2
Neighborhood,3


In [11]:
le1 = LabelEncoder()
df['Brick'] = le1.fit_transform(df['Brick'])
df['Brick'].unique()

le2 = LabelEncoder()
df['Neighborhood'] = le2.fit_transform(df['Neighborhood'])
df['Neighborhood'].unique()

array([0, 1, 2])

In [12]:
df.drop('Home',axis=1,inplace=True)

In [13]:
sc1 = MinMaxScaler()
df[['Price']] = sc1.fit_transform(df[['Price']])

sc2 = MinMaxScaler()
df[['SqFt']] = sc2.fit_transform(df[['SqFt']])

In [14]:
df['Price'] = round(df['Price'],2)
df['SqFt'] = round(df['SqFt'],2)

In [15]:
X = df.drop('Brick',axis=1)
y = df['Brick']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)
print("X_train shape : ",X_train.shape)
print("X_test shape : ",X_test.shape)
print("y_train shape : ",y_train.shape)
print("y_test shape : ",y_test.shape)

X_train shape :  (85, 6)
X_test shape :  (43, 6)
y_train shape :  (85,)
y_test shape :  (43,)


In [17]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(45,activation='relu',input_dim = 6))
model.add(tf.keras.layers.Dense(25,activation='relu'))
model.add(tf.keras.layers.Dense(15,activation='relu'))
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))


In [18]:
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='adam', metrics=['BinaryAccuracy'])

start_train = time.time()
history = model.fit(X_train, y_train, epochs=100)
end_train = time.time()

training_time = end_train - start_train
print(f"Training time: {training_time:.2f} seconds")

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - BinaryAccuracy: 0.7416 - loss: 0.6557
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7065 - loss: 0.6325
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7182 - loss: 0.6191
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7221 - loss: 0.5965
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7299 - loss: 0.5798
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.6830 - loss: 0.6193
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7182 - loss: 0.5845 
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7534 - loss: 0.5560
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7143 - loss: 0.5738
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.6948 - loss: 0.6148
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7182 - loss: 0.5878
Epoch 1

In [19]:
start_test = time.time()
test_loss, test_acc = model.evaluate(X_test, y_test)
end_test = time.time()
testing_time = end_test - start_test
print(f"Testing time: {testing_time:.2f} seconds")

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - BinaryAccuracy: 0.6010 - loss: 0.6326 
Testing time: 0.28 seconds


In [20]:
y_pred = model.predict(X_test)
print(y_pred.shape)
y_bi_pred = (y_pred > 0.5).astype(int).flatten()
print(y_bi_pred.shape)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
(43, 1)
(43,)


In [21]:
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.6046511627906976
Confusion Matrix:
 [[24  1]
 [16  2]]
Classification Report:
               precision    recall  f1-score   support

           0       0.60      0.96      0.74        25
           1       0.67      0.11      0.19        18

    accuracy                           0.60        43
   macro avg       0.63      0.54      0.46        43
weighted avg       0.63      0.60      0.51        43



In [22]:
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='rmsprop', metrics=['BinaryAccuracy'])

start_train = time.time()
history = model.fit(X_train, y_train, epochs=100)
end_train = time.time()

training_time = end_train - start_train
print(f"Training time: {training_time:.2f} seconds")

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - BinaryAccuracy: 0.8278 - loss: 0.4772
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - BinaryAccuracy: 0.8160 - loss: 0.4597
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8102 - loss: 0.5012
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8063 - loss: 0.4824
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8043 - loss: 0.4936
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8082 - loss: 0.4775
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.7770 - loss: 0.4766
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8180 - loss: 0.4720
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8082 - loss: 0.4901
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7887 - loss: 0.4892
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8415 - loss: 0.4475
Epoch 12

In [23]:
y_pred = model.predict(X_test)
print(y_pred.shape)
y_bi_pred = (y_pred > 0.5).astype(int).flatten()
print(y_bi_pred.shape)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step
(43, 1)
(43,)


In [24]:
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.6511627906976745
Confusion Matrix:
 [[25  0]
 [15  3]]
Classification Report:
               precision    recall  f1-score   support

           0       0.62      1.00      0.77        25
           1       1.00      0.17      0.29        18

    accuracy                           0.65        43
   macro avg       0.81      0.58      0.53        43
weighted avg       0.78      0.65      0.57        43



In [25]:
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='adagrad', metrics=['BinaryAccuracy'])

start_train = time.time()
history = model.fit(X_train, y_train, epochs=100)
end_train = time.time()

training_time = end_train - start_train
print(f"Training time: {training_time:.2f} seconds")

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - BinaryAccuracy: 0.8591 - loss: 0.3723
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - BinaryAccuracy: 0.8122 - loss: 0.4669 
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - BinaryAccuracy: 0.8435 - loss: 0.4255
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - BinaryAccuracy: 0.8727 - loss: 0.3682 
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - BinaryAccuracy: 0.8806 - loss: 0.3291
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - BinaryAccuracy: 0.8630 - loss: 0.4082
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - BinaryAccuracy: 0.8571 - loss: 0.3879
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8513 - loss: 0.3936
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8591 - loss: 0.3814
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - BinaryAccuracy: 0.8474 - loss: 0.3973
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8864 - loss: 0.3623 
Epoch

In [26]:
y_pred = model.predict(X_test)
print(y_pred.shape)
y_bi_pred = (y_pred > 0.5).astype(int).flatten()
print(y_bi_pred.shape)

1/2 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
(43, 1)
(43,)


In [27]:
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.6511627906976745
Confusion Matrix:
 [[23  2]
 [13  5]]
Classification Report:
               precision    recall  f1-score   support

           0       0.64      0.92      0.75        25
           1       0.71      0.28      0.40        18

    accuracy                           0.65        43
   macro avg       0.68      0.60      0.58        43
weighted avg       0.67      0.65      0.61        43

